# ./notebook/Dockerfile
FROM jupyter/datascience-notebook
LABEL maintainer "rtbt <hirune525@gmail.com>"
WORKDIR /home/jovyan/work
CMD ["start-notebook.sh", "--NotebookApp.password='sha1:3d01e4558a43:e2a08fdac4d0d6827f0de2186e1f599292cd1d36'", "--NotebookApp.token=''"]

